# Generated by Django 2.2.9 on 2020-01-31 07:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('new_slug', models.CharField(max_length=100, verbose_name='Для ссылки')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('posted', models.DateField(default=django.utils.timezone.now, verbose_name='Опубликовано')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('image1', models.ImageField(upload_to='blog/list', verbose_name='Картинка в индес')),
                ('image2', models.ImageField(blank=True, upload_to='blog/list', verbose_name='главная картинка в деталях')),
            ],
            options={
                'verbose_name_plural': 'новости',
                'verbose_name': 'новость',
                'ordering': ['-posted'],
            },
        ),
    ]
