# Generated by Django 2.2.9 on 2020-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/list')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое содержание')),
            ],
            options={
                'verbose_name_plural': 'Баннеры в разделе новости',
                'verbose_name': 'Баннер в разделе новости',
                'ordering': ['order'],
            },
        ),
    ]
