# Generated by Django 2.2.9 on 2020-02-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomMagicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/list')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Фото с магией внизу страницы',
                'verbose_name_plural': 'Фото с магией внизу страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/list')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое содержание')),
            ],
            options={
                'verbose_name': 'Баннер на главной',
                'verbose_name_plural': 'Баннеры на главной',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediumMagicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/list')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Фото с магией в списке на главной',
                'verbose_name_plural': 'Фото с магией в списке на главной',
                'ordering': ['order'],
            },
        ),
    ]
