# Generated by Django 2.2.9 on 2020-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название для url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/list')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое содержание')),
            ],
            options={
                'verbose_name_plural': 'категории людей',
                'verbose_name': 'категория людей',
                'ordering': ['order', 'name'],
            },
        ),
    ]
