# Generated by Django 2.2.9 on 2020-01-31 07:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('people_slug', models.CharField(max_length=100, verbose_name='Для ссылки')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('posted', models.DateField(default=django.utils.timezone.now, verbose_name='Опубликовано')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('index_image', models.ImageField(upload_to='peoples/list', verbose_name='Картинка в индекс')),
                ('image', models.ImageField(blank=True, upload_to='peoples/list', verbose_name='Главная картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'люди',
                'verbose_name': 'человек',
                'ordering': ['-posted'],
            },
        ),
    ]
